// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkp3sy7Ms88i6kZgiWIhVfq_kaAT3L_zI',
    appId: '1:284214713620:web:5019861941e47c1c013601',
    messagingSenderId: '284214713620',
    projectId: 'newproj-87a10',
    authDomain: 'newproj-87a10.firebaseapp.com',
    storageBucket: 'newproj-87a10.appspot.com',
    measurementId: 'G-22K042H0MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUhj1-aDOyXyuBXWRKj9hDR5GuZSXk_lg',
    appId: '1:284214713620:android:c098af6c9e5bbe1d013601',
    messagingSenderId: '284214713620',
    projectId: 'newproj-87a10',
    storageBucket: 'newproj-87a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArbxtho5y4aJyULxZB4Rc8YagJmLXhS9c',
    appId: '1:284214713620:ios:016f5e04a58af258013601',
    messagingSenderId: '284214713620',
    projectId: 'newproj-87a10',
    storageBucket: 'newproj-87a10.appspot.com',
    iosBundleId: 'com.example.loveapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArbxtho5y4aJyULxZB4Rc8YagJmLXhS9c',
    appId: '1:284214713620:ios:016f5e04a58af258013601',
    messagingSenderId: '284214713620',
    projectId: 'newproj-87a10',
    storageBucket: 'newproj-87a10.appspot.com',
    iosBundleId: 'com.example.loveapp',
  );
}
